spring.application.name=demo
server.port=8080

slack.bot.token=xoxb-10030417129909-10044521045860-ZbgH3nnIUujQi6aDgqWaQiYC
freshdesk.domain=warpdrivetech.freshdesk.com
freshdesk.api.key=uRilzNxEetTuGyMOEwtv
